// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiMzhrOV6tMeNjuBOv8FGD4c_SL0rN7Xg',
    appId: '1:808539772933:web:8f5f4c9b93d9b37f74646c',
    messagingSenderId: '808539772933',
    projectId: 'iizmotabar-flutter-brew',
    authDomain: 'iizmotabar-flutter-brew.firebaseapp.com',
    storageBucket: 'iizmotabar-flutter-brew.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf-BMcN2aVN44BM4oqg0fY5rFXGtFIMAg',
    appId: '1:808539772933:android:80cfc50b73d9111c74646c',
    messagingSenderId: '808539772933',
    projectId: 'iizmotabar-flutter-brew',
    storageBucket: 'iizmotabar-flutter-brew.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHocFJSFQrc4nC21w93Uh_ZLTXy3u_mZE',
    appId: '1:808539772933:ios:241a15165b6abfb674646c',
    messagingSenderId: '808539772933',
    projectId: 'iizmotabar-flutter-brew',
    storageBucket: 'iizmotabar-flutter-brew.appspot.com',
    iosClientId: '808539772933-qqkgs0eurjuhv32cstile0upgeoebgds.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHocFJSFQrc4nC21w93Uh_ZLTXy3u_mZE',
    appId: '1:808539772933:ios:241a15165b6abfb674646c',
    messagingSenderId: '808539772933',
    projectId: 'iizmotabar-flutter-brew',
    storageBucket: 'iizmotabar-flutter-brew.appspot.com',
    iosClientId: '808539772933-qqkgs0eurjuhv32cstile0upgeoebgds.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewApp',
  );
}
